FROM node:18.18.2 as build-stage

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    git \
    && pip install pytest coverage

COPY /team_three_star/ /uno/

WORKDIR /uno

CMD ["python", "random_game.py"]
