[tool.poetry]
name = "poetry-back-end"
version = "0.1.0"
description = ""
authors = ["Huy"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
